<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DFe.Classes\DFe.Classes.csproj" />
    <ProjectReference Include="..\DFe.Utils\DFe.Utils.csproj" />
    <ProjectReference Include="..\MDFe.Classes\MDFe.Classes.csproj" />
    <ProjectReference Include="..\MDFe.Servicos\MDFe.Servicos.csproj" />
    <ProjectReference Include="..\MDFe.Utils\MDFe.Utils.csproj" />
    <ProjectReference Include="..\MDFe.Wsdl\MDFe.Wsdl.csproj" />
  </ItemGroup>

</Project>
